### ISSUE TITLE
filterBcConns = true doesn't work 

### ISSUE THREAD

**Issue by areebbeigh** [yjs/y-webrtc#10]
Using `filterBcConns: true` in options still uses broadcast channels instead of a webrtc connection for tabs in the same browser. Tested on `Chrome: Version 79.0.3945.79 (Official Build) (64-bit)` and `Firefox: 74.0 (64-bit)` on Ubuntu 18.04

**Comment by diegodorado** [comment]
the same happens to me.
I believe the option should be `disableBroadcastChannels` and do not even subscribe/unsuscribe on connect/disconnect

**Comment by areebbeigh** [comment]
I suppose I wasn't paying enough attention. `filterBcConns: false` is what makes sense if I want browser tabs to user `webRTCConns`.  I think the [readme has it wrong](https://github.com/yjs/y-webrtc#use-y-webrtc-for-conferencing-solutions). The default value in the constructor is true.

**Comment by dmonad** [comment]
All Yjs connectors use broadcastchannels to exchange document updates efficiently window-to-window. It is a cheap method to exchange document updates when no internet connection is available.

It doesn't make sense to me to disable the broadcastchannel (there is no advantage in that).
Creating a webrtc connection instead of a broadcastchannel will just delay syncing. Furthermore, it is not possible to create WebRTC connection without a network connection.

The documentation clearly says:

> Whether to create WebRTC connections to other tabs in the same browser.

The idea is that a WebRTC connection is only created if the client is not already connected via broadcastchannel. Therefore, `filterBcConns`.

But you are right @areebbeigh . The mentioned section is wrong.

But you are
