### ISSUE TITLE
Node lock version

### ISSUE THREAD

**Issue by vwall** [yjs/y-webrtc#4]
Trying to install this and getting an error that it requires node version 10.  Downgrade to v10 and it complains about 
```error lib0@0.2.13: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.19.0"```

**Comment by dmonad** [comment]
Try upgrading lib0 to `0.2.14` - it is now compatible with node v10. `npm upgrade`

**Comment by vwall** [comment]
Any reason for locking it to v10?

**Comment by dmonad** [comment]
Testing more versions takes too much time. The initial idea was that lib0 should be a esm module, which is why I locked it to v12. But now I'm going to maintain it as a normal cjs module. Just reply if you have still problems. If there are good reasons to support older node versions just open a new ticket in lib0.
